"""
app.py -- Collaborative Outcome Tracker (Streamlit prototype)
Professional, calm visual design suited to a counselling context.

Run locally:
    streamlit run app.py

Requirements:
    pip install streamlit pandas altair sentence-transformers requests

Expects synthetic_data/{clients,goals,sessions}.csv in ../synthetic_data/
(generated by generate_synthetic_data.py)
"""

import os

import altair as alt
import pandas as pd
import streamlit as st

from mismatch_detector import MismatchDetector

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "..", "synthetic_data")

st.set_page_config(page_title="Outcome Tracker", layout="wide", initial_sidebar_state="collapsed")

# ---------------------------------------------------------------------------
# Design tokens
# ---------------------------------------------------------------------------
INK = "#12181F"
SURFACE = "#1A222C"
SAGE = "#6FA98D"
SAGE_DIM = "#4C7D66"
AMBER = "#E8A857"
TEXT = "#E7EAEE"
TEXT_MUTED = "#8C97A6"
BORDER = "#2C3744"

st.markdown(f"""
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Lora:wght@500;600&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">

<style>
.stApp {{
    background-color: {INK};
    color: {TEXT};
    font-family: 'Inter', sans-serif;
}}
h1, h2, h3 {{
    font-family: 'Lora', serif;
    font-weight: 600;
    color: {TEXT};
}}
.hero-title {{
    font-family: 'Lora', serif;
    font-size: 2.1rem;
    font-weight: 600;
    color: {TEXT};
    margin-bottom: 0.1rem;
}}
.hero-sub {{
    font-family: 'Inter', sans-serif;
    color: {TEXT_MUTED};
    font-size: 0.95rem;
    margin-bottom: 1.8rem;
}}
.client-line {{
    font-family: 'Inter', sans-serif;
    color: {TEXT_MUTED};
    font-size: 0.9rem;
    border-bottom: 1px solid {BORDER};
    padding-bottom: 0.9rem;
    margin-bottom: 0.4rem;
}}
.urgency-low {{ color: {SAGE}; font-weight: 600; }}
.urgency-moderate {{ color: {AMBER}; font-weight: 600; }}
.urgency-high {{ color: #D9765A; font-weight: 600; }}

.goal-block {{
    border-left: 3px solid {SAGE_DIM};
    padding: 0.3rem 0 0.3rem 1.1rem;
    margin: 1.6rem 0 1.1rem 0;
}}
.goal-title {{
    font-family: 'Lora', serif;
    font-size: 1.25rem;
    color: {TEXT};
    margin-bottom: 0.3rem;
}}
.goal-meta {{
    font-size: 0.87rem;
    color: {TEXT_MUTED};
    line-height: 1.6;
}}
.goal-meta b {{ color: {TEXT}; font-weight: 500; }}

.flag-row {{
    border-left: 3px solid {AMBER};
    background-color: {SURFACE};
    padding: 0.8rem 1rem;
    margin: 0.6rem 0;
    border-radius: 0 4px 4px 0;
}}
.flag-header {{
    font-size: 0.88rem;
    color: {AMBER};
    font-weight: 600;
    margin-bottom: 0.35rem;
}}
.flag-detail {{
    font-size: 0.85rem;
    color: {TEXT_MUTED};
    line-height: 1.7;
}}
.flag-detail b {{ color: {TEXT}; font-weight: 500; }}
.review-note {{
    font-size: 0.8rem;
    color: {TEXT_MUTED};
    font-style: italic;
    margin-top: 0.4rem;
}}

.summary-line {{
    font-size: 0.95rem;
    color: {TEXT};
    margin: 0.8rem 0;
    padding: 0.7rem 1rem;
    background-color: {SURFACE};
    border-radius: 4px;
}}

div[data-testid="stSelectbox"] label {{
    color: {TEXT_MUTED} !important;
    font-size: 0.85rem;
}}
.stButton > button {{
    background-color: {SAGE_DIM};
    color: {TEXT};
    border: none;
    border-radius: 4px;
    font-family: 'Inter', sans-serif;
    font-weight: 500;
    padding: 0.5rem 1.1rem;
}}
.stButton > button:hover {{
    background-color: {SAGE};
    color: {INK};
}}
[data-testid="stExpander"] {{
    background-color: {SURFACE};
    border: 1px solid {BORDER};
    border-radius: 4px;
}}
.status-badge {{
    display: inline-block;
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.15rem 0.6rem;
    border-radius: 10px;
    margin-left: 0.6rem;
}}
.status-active {{ background-color: rgba(111,169,141,0.18); color: {SAGE}; }}
.status-achieved {{ background-color: rgba(111,169,141,0.32); color: {SAGE}; }}
.status-needs-revision {{ background-color: rgba(232,168,87,0.22); color: {AMBER}; }}
.status-pending {{ background-color: rgba(140,151,166,0.2); color: {TEXT_MUTED}; }}

.ai-tag {{
    font-size: 0.78rem;
    color: {TEXT_MUTED};
    border: 1px solid {BORDER};
    border-radius: 4px;
    padding: 0.3rem 0.7rem;
    display: inline-block;
    margin-top: 0.3rem;
}}
.ai-tag b {{ color: {SAGE}; font-weight: 600; }}
hr {{ border-color: {BORDER}; }}
</style>
""", unsafe_allow_html=True)


@st.cache_data
def load_data():
    clients = pd.read_csv(os.path.join(DATA_DIR, "clients.csv"))
    goals = pd.read_csv(os.path.join(DATA_DIR, "goals.csv"))
    sessions = pd.read_csv(os.path.join(DATA_DIR, "sessions.csv"))
    return clients, goals, sessions


@st.cache_resource
def load_detector():
    return MismatchDetector(use_ollama=True)


clients, goals, sessions = load_data()

st.markdown('<div class="hero-title">Outcome Tracker</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="hero-sub">Progress measured against goals the client defined — not attendance.</div>',
    unsafe_allow_html=True,
)
st.markdown(
    '<div class="ai-tag">Powered by <b>sentence-transformers</b> (all-MiniLM-L6-v2) for mismatch detection '
    'and <b>Ollama · llama3.2:1b</b> (local, on-device) for counsellor-facing explanations. '
    'No client data leaves this machine.</div>',
    unsafe_allow_html=True,
)
st.markdown("<br>", unsafe_allow_html=True)

client_ids = clients["client_id"].tolist()
client_labels = {row["client_id"]: f'{row["client_id"]} — {row["client_name"]}' for _, row in clients.iterrows()}
selected_client = st.selectbox(
    "Client", client_ids, format_func=lambda cid: client_labels[cid], label_visibility="collapsed"
)

client_row = clients[clients["client_id"] == selected_client].iloc[0]
client_goals = goals[goals["client_id"] == selected_client]

urgency = client_row["urgency_level"]
urgency_class = f"urgency-{urgency}"
st.markdown(
    f'<div class="client-line"><b style="color:{TEXT}; font-size:1.05rem;">{client_row["client_name"]}</b> '
    f'<span style="color:{TEXT_MUTED};">({selected_client})</span> '
    f'&nbsp;·&nbsp; <span class="{urgency_class}">{urgency} urgency</span> '
    f'&nbsp;·&nbsp; {client_row["presenting_concern"]}</div>',
    unsafe_allow_html=True,
)

if client_goals.empty:
    st.markdown('<div class="summary-line">No goals recorded for this client yet.</div>', unsafe_allow_html=True)
else:
    for _, goal in client_goals.iterrows():
        status = goal.get("status", "active")
        status_class = f"status-{status.replace(' ', '-')}"
        st.markdown(f"""
        <div class="goal-block">
            <div class="goal-title">{goal['goal_text']} <span class="status-badge {status_class}">{status}</span></div>
            <div class="goal-meta">
                <b>Baseline</b> — {goal['baseline']}<br>
                <b>Target</b> — {goal['target']} &nbsp;·&nbsp; by {goal['target_date']}
            </div>
        </div>
        """, unsafe_allow_html=True)

        goal_sessions = sessions[sessions["goal_id"] == goal["goal_id"]].sort_values("session_date")

        if goal_sessions.empty:
            st.markdown('<div class="summary-line">No sessions logged yet.</div>', unsafe_allow_html=True)
            continue

        chart = (
            alt.Chart(goal_sessions)
            .mark_line(point=alt.OverlayMarkDef(color=SAGE, size=45), color=SAGE, strokeWidth=2.2)
            .encode(
                x=alt.X("session_date:T", title=None, axis=alt.Axis(labelColor=TEXT_MUTED, gridColor=BORDER)),
                y=alt.Y("self_reported_rating:Q", title="self-reported rating",
                        axis=alt.Axis(labelColor=TEXT_MUTED, titleColor=TEXT_MUTED, gridColor=BORDER),
                        scale=alt.Scale(domain=[0, 10])),
            )
            .properties(height=200, background=INK)
            .configure_view(strokeWidth=0)
        )
        st.altair_chart(chart, use_container_width=True)

        run_check = st.button("Run mismatch check", key=f"btn_{goal['goal_id']}")

        if run_check:
            detector = load_detector()
            with st.spinner("Comparing self-reported progress against session evidence..."):
                results = [detector.check_session(row.to_dict()) for _, row in goal_sessions.iterrows()]

            flagged = [r for r in results if r.is_flagged]
            st.markdown(
                f'<div class="summary-line">{len(flagged)} of {len(results)} sessions flagged for review.</div>',
                unsafe_allow_html=True,
            )

            for r in flagged:
                session_row = goal_sessions[goal_sessions["session_id"] == r.session_id].iloc[0]
                explanation = r.explanation or "No explanation generated."
                st.markdown(f"""
                <div class="flag-row">
                    <div class="flag-header">{r.session_id} — {session_row['session_date']}</div>
                    <div class="flag-detail">
                        <b>Rating</b> {session_row['self_reported_rating']}/10 &nbsp;·&nbsp;
                        <b>Reported</b> "{session_row['self_reported_text']}"<br>
                        <b>Barriers</b> {session_row['barriers']}<br>
                        <b>Why flagged</b> {', '.join(r.reasons)} (similarity {r.similarity_score})<br>
                        <b>Counsellor note</b> {explanation}
                    </div>
                    <div class="review-note">Flagged for human review only — no conclusion is drawn automatically.</div>
                </div>
                """, unsafe_allow_html=True)

        with st.expander("Full session log"):
            st.dataframe(
                goal_sessions[["session_id", "session_date", "self_reported_rating",
                                "self_reported_text", "barriers", "agreed_adjustment"]],
                use_container_width=True,
                hide_index=True,
            )